---
title: "nba2017, stats, data dictionary"
author: "Pinshuo Ye"
date: "10/12/2017"
output: github_document
---


## Data Dictionary of NBA2017 Player Statistics

### Data Dictionary:

**Vector**     |   **Meaning**                                            |  **Unit**
--------------:|:--------------------------------------------------------:|:------------
  player       | First and last name of player                            | character
  games played | Games Played during regular season                       | games
  minute       | Minutes played during regular seaon                      | minutes
  field_goals_made| Field Goals Made                                      | number
  field_goals_atts| Field Goal Attempts                                   | number
  field_goals_perc| The percentage of the field goals                     | percentage
  points3_made | 3-point Field Goals                                      | number
  points3_atts | 3-point Field Goal Attempts                              | number
  points3_perc | The percentage of 3-pointers                             | percentage
  points2_made | 2-point Field Goals                                      | number
  Points2_atts | 2-point Field Goal Attempts                              | number
  points2_perc | The percentage of 2-points                               | percentage
  points1_made | Free Throws Made                                         | number
  points1_atts | Free Throw Attempts                                      | number
  points1_perc | The percentage of free throw made                        | percentage
  off_rebounds | Offensive Rebounds                                       | number
  def_rebounds | Defensive Rebounds                                       | number
  assists      | Assists                                                  | number
  steals       | Steals                                                   | number
  blocks       | Blocks                                                   | number
  turnovers    | Turnovers                                                | number



### Details
* The data is downloaded from professor Sanchez`s github repository.
* The link of the data is :[https://github.com/ucb-stat133/stat133-fall-2017/blob/master/data/nba2017-stats.csv](https://github.com/ucb-stat133/stat133-fall-2017/blob/master/data/nba2017-stats.csv)